name: Tests
on:
  push:
    # the pull_request target triggers on pushes already, so this branches
    # constraint ensures we don't run CI twice per push to a PR
    branches: [ master, main ]

  pull_request:
    # the constraint is optional, it will likely not matter much for a simple
    # one-trunk development workflow
    branches: [ master, main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Probe runner package cache
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: cargo
          version: 1.0

      - name: Install tytanic from crates.io
        uses: baptiste0928/cargo-install@v2.2.0
        with:
          crate: tytanic
          version: 0.1.3

      - name: Run test suite
        run: tt run --no-fail-fast

      - name: Archive diffs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: diffs
          path: |
            tests/**/diff/*.png
            tests/**/out/*.png
            tests/**/ref/*.png
          retention-days: 5
